import "~/styles/globals.css";

import { type Metadata } from "next";
import {  Inter } from "next/font/google";
import Provider from "~/components/Provider";
import { Toaster } from "~/components/ui/sonner";




export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const inter = Inter({
  subsets: ["latin"],

});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`min-h-screen ${inter.className}`}>
      <body className="h-full">
        <Provider>
          <Toaster/>
          <main className="flex w-full">{children}</main>
        </Provider>
      </body>
    </html>
  );
}
