import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import Provider from "~/components/Provider";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`min-h-screen ${geist.variable}`}>
      <body className="h-full">
        <Provider >
          <main className="w-full flex ">
        
            {children}
          
          </main>
          </Provider>
      </body>
    </html>
  );
}
